rango/urls.py
from django.conf.urls import patterns, url
from rango import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.category, name='category'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^restricted/$', views.restricted, name='restricted'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^about/$', views.about, name='about'),
)

rango_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from registration.backends.simple.views import RegistrationView

class MyRegistrationView(RegistrationView):
    def get_success_url(self, request=None, user=None):
        return '/rango/'


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'rango_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^rango/', include('rango.urls', namespace='rango')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)', 'serve', {'document_root': settings.MEDIA_ROOT})
    )

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User)

    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __unicode__(self):
        return self.user.username

rango/forms.py
from django import forms
from models import Category, Page, User, UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter page title")
    url = forms.URLField(max_length=200, help_text="Please enter page URL")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('htp://'):
            url = 'http://' + url
            cleaned_data['url'] = url

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from django.shortcuts import render
from models import Category, Page
from forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from datetime import datetime

def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {''
        'boldmessage': "I am bold font from the context",
        'categories': category_list,
        'pages': page_list,
    }
    visits = int(request.COOKIES.get('visits', '1'))
    reset_last_visit_time = False
    response = render(request, 'rango/index.html', context_dict)
    if 'last_visit' in request.COOKIES:
        last_visit = request.COOKIES['last_visit']
        print ">>>>"+str(type(last_visit))
        last_visit_time = datetime.strptime(last_visit[:-7], "%Y-%m-%d %H:%M:%S")

        if (datetime.now() - last_visit_time).days > 0:
            visits += 1
            reset_last_visit_time = True
    else:
        reset_last_visit_time = True
        context_dict['visits'] = visits
        response = render(request, 'rango/index.html', context_dict)

    if reset_last_visit_time:
        response.set_cookie('last_visit', datetime.now())
        response.set_cookie('visits', visits)
    return response

def about(request):
    return render(request, 'rango/about.html', {})

def category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        context_dict['category_name'] = category.name

        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category
        context_dict['category_slug'] = category_name_slug
    except Category.DoesNotExist:
        pass

    return render(request, 'rango/category.html', context_dict)

def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print form.errors
    else:
        form = CategoryForm()
    return render(request, 'rango/add_category.html', {'form': form})

def add_page(request, category_name_slug):
    try:
        cat = Category.objects.get(slug = category_name_slug)
    except Category.DoesNotExist:
        cat = None

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if cat:
                page = form.save(commit=False)
                page.category = cat
                page.views = 0
                page.save()
                return category(request, category_name_slug)
        else:
            print form.errors
    else:
        form = PageForm()

    context_dict = {'form': form, 'category': cat, 'slug': category_name_slug}

    return render(request, 'rango/add_page.html', context_dict)

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            registered = True

        else:
            print user_form.errors, profile_form.errors

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'rango/register.html',
                  {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/rango/')
            else:
                return HttpResponse("Your Rango account is disabled")
        else:
            print "Invalid login details: {0}, {1}".format(username, password)
    else:
        return render(request, 'rango/login.html', {})

@login_required
def restricted(request):
    return HttpResponse("Since you're loggedin, you can see this text!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/rango/')

rango/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title %}About{% endblock %}

{% block body_block %}

    <p>This is the about page</p>
{% endblock %}

rango/templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title %}Add Category{% endblock %}

{% block body_block %}
    <h1>Add a category</h1>
    <form id="category_form" method="post" action="{% url 'rango:add_category' %}">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Create Category">
    </form>
{% endblock %}

rango/templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title %}Add Page{% endblock %}

{% block body_block %}

    {% if category %}
        <h1>Add a Page</h1>
        <form id="page_form" method="post" action="{% url 'rango:add_page' slug %}">
            {% csrf_token %}
            {% for hidden in forms.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Add Page">
        </form>
    {% else %}
        <strong>Category does not exist</strong>
    {% endif %}
{% endblock %}

rango/templates/rango/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rango - {% block title %}How to Tango with Django!{% endblock %}</title>
</head>
<body>
    <div>
        {% block body_block %}{% endblock %}
    </div>
    <hr>
    <div>
        <ul>
            {% if user.is_authenticated %}
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                <li><a href="{% url 'rango:add_category' %}">Add new Category</a></li>
            {% else %}
                <li><a href="{% url 'registration_register' %}">Register Here</a></li>
                <li><a href="{% url 'auth_login' %}">Login</a></li>
            {% endif %}
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="/rango/">Home</a></li>
        </ul>
    </div>
</body>
</html>

rango/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title %}{{ category_name }}{% endblock %}

{% block body_block %}
    <h1>{{ category_name }}</h1>
    <a href="{% url 'rango:add_page' category_slug %}">Add Page</a>
    {% if category %}
        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <strong>No pages currently in category</strong>
        {% endif %}
    {% else %}
        <strong>The specified category does not exist</strong>
    {% endif %}
{% endblock %}

rango/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title %}{% endblock %}

{% block body_block %}
    {% if user.is_authenticated %}
        <h1>Rango says... Hello {{ user.username }}!</h1>
        <a href="{% url 'rango:restricted' %}">Restricted Page</a>
        <a href="{% url 'rango:logout' %}">Logout</a>
    {% else %}
        <h1>Rango says... Hello World!</h1>
        <a href="{% url 'rango:login' %}">Login</a>
        <a href="{% url 'rango:register' %}">Register Here</a>
    {% endif %}

    <a href="{% url 'rango:add_category' %}">Add new category</a>

    <h3>Categories</h3>
    {% if categories %}
        <ul>
            {% for category in categories %}
                <li><a href="{% url 'rango:category' category.slug %}">{{ category.name }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <strong>No categories present</strong>
    {% endif %}

    <h3>Pages</h3>
    {% if pages %}
        <ul>
            {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <strong>No pages present</strong>
    {% endif %}
{% endblock %}

rango/templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title %}Login{% endblock %}

{% block body_block %}

    <h1>Login to Rango</h1>
    <form id="login_form" method="post" action="{% url 'rango:login' %}">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50">
        <br>
        Password: <input type="text" name="password" value="" size="50">
        <br>
        <input type="submit" value="submit">
    </form>
{% endblock %}

rango/templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title %}Register{% endblock %}

{% block body_block %}

    <h1>Register with Rango</h1>

    {% if registered %}
        <p>Rango says: <strong>thank You for registering!</strong></p>
        <a href="/rango/">Return to homepage</a>
    {% else %}
        <p>Rango says: <strong>register here!</strong></p>
        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type="submit" name="submit" value="Register">
        </form>
    {% endif %}
{% endblock %}